version: 2

jobs:
  wpcs:
      docker:
        - image: notnoopci/php:7.0-apache-node
      steps:
        - checkout
        - run:
            name: Install WPCS
            command: |
              sudo composer self-update
              composer install
        - run:
            name: Run WPCS
            command: vendor/bin/phpcs

workflows:
  version: 2
  test_and_standards:
    jobs:
      - wpcs:
          filters:
            branches:
              ignore: develop